---
- name: Install Docker
  gather_facts: No
  hosts: localhost
  become: yes
  become_method: sudo
 
  tasks:
    - name: Install yum utils
      yum:
        name: yum-utils
        state: latest

    - name: Install lvm2
      yum:
        name: lvm2
        state: latest

    - name: Install device-mapper-libs
      yum:
        name: device-mapper-libs
        state: latest

    - name: Install device-mapper-event-libs
      yum:
        name: device-mapper-event-libs
        state: latest

    - name: Install device-mapper-persistent-data
      yum:
        name: device-mapper-persistent-data
        state: latest

    - name: Install selinux
      yum:
        name: http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.107-3.el7.noarch.rpm
        state: latest
  
    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker
      package:
        name: docker-ce
        state: latest

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install easy_install
      yum:
        name: python-setuptools

    - name: Install virtualenv
      easy_install:
        name: virtualenv

    - name: Install pip
      yum:
        name: python-pip

    - name: Install docker
      pip:
        name: docker

    - name: Add group "docker" to remote server
      group:
        name: docker
        state: present

    - name: Add user "psapp" to "docker" group
      user:
        name: psapp
        groups: docker
        append: yes
